// Application: Period Control Service
// Orchestrates Year -> Month -> Date periods with tenant isolation and audit logging
// AGENTS.md Rule 6, 7, 12, 25 & AGENTS1.md Rule 4

import { periodRepository } from '../infrastructure/PeriodRepository';
import { 
  ReportingYear, 
  MonthlyPeriod, 
  DailyPeriodDate 
} from '../domain/PeriodSpecification';
import { UserAuthContext } from '@/shared/auth';
import { ForbiddenError, ValidationError } from '@/shared/errors';
import { AuditService } from '@/modules/audit';
import { AUDIT_ACTIONS, ROLES } from '@/shared/constants';
import { logger } from '@/shared/logger';

export class PeriodService {
  /**
   * Retrieves reporting years scoped to user's authorized company.
   */
  public static async getYears(
    companyIdParam: string | null | undefined,
    actor: UserAuthContext
  ): Promise<ReportingYear[]> {
    const effectiveCompanyId = actor.role === ROLES.SUPER_ADMIN
      ? (companyIdParam && companyIdParam !== 'ALL' ? companyIdParam : null)
      : (actor.companyId || null);

    return await periodRepository.getYears(effectiveCompanyId);
  }

  /**
   * Creates a new reporting year.
   */
  public static async createYear(
    data: { companyId?: string; year: number; status?: string; notes?: string; autoGenerate?: boolean },
    actor: UserAuthContext
  ): Promise<ReportingYear> {
    if (actor.role !== ROLES.SUPER_ADMIN && actor.role !== ROLES.COMPANY_ADMIN) {
      throw new ForbiddenError('Only Super Admin or Company Admin can create reporting years');
    }

    const companyId = actor.role === ROLES.SUPER_ADMIN
      ? (data.companyId || actor.companyId)
      : actor.companyId;

    if (!companyId) {
      throw new ValidationError('Company ID is required to create reporting year');
    }

    if (!data.year || data.year < 2020 || data.year > 2050) {
      throw new ValidationError('Valid year between 2020 and 2050 is required');
    }

    let yearRecord: ReportingYear;
    if (data.autoGenerate !== false) {
      // Auto-generates Year + 12 Months + 365 Days
      await periodRepository.autoCreatePeriod(companyId, data.year);
      const years = await periodRepository.getYears(companyId);
      yearRecord = years.find((y) => y.year === data.year) || {
        id: 'new',
        company_id: companyId,
        year: data.year,
        status: 'ACTIVE',
        is_locked: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      };
    } else {
      yearRecord = await periodRepository.createYear(companyId, data.year, data.status || 'ACTIVE', data.notes);
    }

    await AuditService.logEvent({
      userId: actor.id,
      companyId,
      eventType: AUDIT_ACTIONS.CREATE,
      entityName: 'reporting_years',
      entityId: String(data.year),
      newValues: { year: data.year, autoGenerated: data.autoGenerate },
    });

    return yearRecord;
  }

  /**
   * Updates reporting year status.
   */
  public static async updateYear(
    id: string,
    updates: { status?: string; is_locked?: boolean; notes?: string },
    actor: UserAuthContext
  ): Promise<ReportingYear> {
    if (actor.role !== ROLES.SUPER_ADMIN && actor.role !== ROLES.COMPANY_ADMIN) {
      throw new ForbiddenError('Only Super Admin or Company Admin can update reporting years');
    }

    const updated = await periodRepository.updateYear(id, updates);

    await AuditService.logEvent({
      userId: actor.id,
      companyId: updated.company_id,
      eventType: AUDIT_ACTIONS.UPDATE,
      entityName: 'reporting_years',
      entityId: id,
      newValues: updates,
    });

    return updated;
  }

  /**
   * Deletes reporting year.
   */
  public static async deleteYear(id: string, actor: UserAuthContext): Promise<void> {
    if (actor.role !== ROLES.SUPER_ADMIN) {
      throw new ForbiddenError('Only Super Admin can delete reporting years');
    }

    await periodRepository.deleteYear(id);

    await AuditService.logEvent({
      userId: actor.id,
      companyId: actor.companyId || null,
      eventType: AUDIT_ACTIONS.DELETE,
      entityName: 'reporting_years',
      entityId: id,
    });
  }

  /**
   * Retrieves 12 monthly periods for a year.
   */
  public static async getMonths(
    year: number,
    companyIdParam: string | null | undefined,
    actor: UserAuthContext
  ): Promise<MonthlyPeriod[]> {
    const effectiveCompanyId = actor.role === ROLES.SUPER_ADMIN
      ? (companyIdParam && companyIdParam !== 'ALL' ? companyIdParam : null)
      : (actor.companyId || null);

    let months = await periodRepository.getMonths(year, effectiveCompanyId);

    // Auto-create fallback if no months exist for requested year
    if (months.length === 0 && effectiveCompanyId) {
      await periodRepository.autoCreatePeriod(effectiveCompanyId, year);
      months = await periodRepository.getMonths(year, effectiveCompanyId);
    }

    return months;
  }

  /**
   * Updates a monthly period.
   */
  public static async updateMonth(
    id: string,
    updates: { working_days?: number; status?: string; is_locked?: boolean; notes?: string },
    actor: UserAuthContext
  ): Promise<MonthlyPeriod> {
    if (actor.role !== ROLES.SUPER_ADMIN && actor.role !== ROLES.COMPANY_ADMIN) {
      throw new ForbiddenError('Only Super Admin or Company Admin can configure monthly periods');
    }

    const updated = await periodRepository.updateMonth(id, updates);

    await AuditService.logEvent({
      userId: actor.id,
      companyId: updated.company_id,
      eventType: AUDIT_ACTIONS.UPDATE,
      entityName: 'working_days',
      entityId: id,
      newValues: updates,
    });

    return updated;
  }

  /**
   * Retrieves daily period dates for a given month and year.
   */
  public static async getDates(
    year: number,
    month: number,
    companyIdParam: string | null | undefined,
    actor: UserAuthContext
  ): Promise<DailyPeriodDate[]> {
    const effectiveCompanyId = actor.role === ROLES.SUPER_ADMIN
      ? (companyIdParam && companyIdParam !== 'ALL' ? companyIdParam : null)
      : (actor.companyId || null);

    return await periodRepository.getDates(year, month, effectiveCompanyId);
  }

  /**
   * Updates a daily period date.
   */
  public static async updateDate(
    identifier: string | { id?: string; companyId?: string | null; date?: string },
    updates: { is_working_day?: boolean; is_locked?: boolean; status?: string; holiday_name?: string | null },
    actor: UserAuthContext
  ): Promise<DailyPeriodDate> {
    if (actor.role !== ROLES.SUPER_ADMIN && actor.role !== ROLES.COMPANY_ADMIN) {
      throw new ForbiddenError('Only Super Admin or Company Admin can configure daily periods');
    }

    const updated = await periodRepository.updateDate(identifier, updates);
    if (!updated) {
      throw new NotFoundError('Reporting date record not found');
    }

    await AuditService.logEvent({
      userId: actor.id,
      companyId: updated.company_id,
      eventType: AUDIT_ACTIONS.UPDATE,
      entityName: 'reporting_dates',
      entityId: updated.id,
      newValues: updates,
    });

    return updated;
  }

  /**
   * Triggers 1-click auto-generation of Year -> 12 Months -> All 365 Days.
   */
  public static async autoCreatePeriod(
    companyIdParam: string | null | undefined,
    year: number,
    defaultWorkingDays: number = 26,
    actor: UserAuthContext
  ): Promise<any> {
    if (actor.role !== ROLES.SUPER_ADMIN && actor.role !== ROLES.COMPANY_ADMIN) {
      throw new ForbiddenError('Only Super Admin or Company Admin can auto-create reporting periods');
    }

    const companyId = actor.role === ROLES.SUPER_ADMIN
      ? (companyIdParam && companyIdParam !== 'ALL' ? companyIdParam : actor.companyId)
      : actor.companyId;

    if (!companyId) {
      throw new ValidationError('Company ID is required to auto-create reporting period');
    }

    const result = await periodRepository.autoCreatePeriod(companyId, year, defaultWorkingDays);

    await AuditService.logEvent({
      userId: actor.id,
      companyId,
      eventType: AUDIT_ACTIONS.CREATE,
      entityName: 'reporting_periods',
      entityId: String(year),
      newValues: { action: 'AUTO_CREATE_PERIOD', year, defaultWorkingDays, result },
    });

    logger.info(`Auto-created reporting period for company ${companyId}, year ${year}`, 'PeriodService');
    return result;
  }

  /**
   * Checks if period is open for data entry.
   */
  public static async checkPeriodOpen(companyId: string, dateStr: string): Promise<{ isOpen: boolean; reason?: string }> {
    return await periodRepository.checkPeriodStatus(companyId, dateStr);
  }
}
